project_id = "btarlycwkcyjaqvvvnvx"

[functions.assemble-character]
verify_jwt = true

[functions.on-workout-logged]
verify_jwt = true

[functions.buy-item]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.leave-challenge]
verify_jwt = true
